import type { CalendarId } from '../lib/calendarRegistry';

export const CALENDAR_NAMES: Record<CalendarId, string> = {
  gregorian: 'Gregorian Calendar',
  julian: 'Julian Calendar',
  ethiopian: 'Ethiopian Calendar',
  coptic: 'Coptic Calendar',
  chinese: 'Chinese Calendar',
  vietnamese: 'Vietnamese Lunisolar Calendar',
  soviet: 'Soviet Revolutionary Calendar',
  frc: 'French Republican Calendar',
  maya: 'Maya Calendar',
  islamic: 'Islamic Calendar',
  hebrew: 'Hebrew Calendar',
  persian: 'Persian Calendar',
  shahanshahi: 'Shahanshahi Calendar',
  bahai: 'Baháʼí Calendar',
  japanese: 'Japanese Wareki Calendar',
  minguo: 'Minguo Calendar',
  koreanDangi: 'Korean Dangi Calendar',
  juche: 'Juche Calendar',
  thaiBuddhist: 'Thai Buddhist Calendar',
  bengali: 'Bengali Calendar',
  nepali: 'Nepali Calendar',
  isoWeek: 'ISO Week Date',
  discordian: 'Discordian Calendar',
  indianCivil: 'Indian Civil Calendar',
  julianDay: 'Julian Day',
};
